### ISSUE TITLE
Doesn't seem to support Inno Setup 6.x?

### ISSUE THREAD

**Issue by edwinyzh** [jrathlev/InnoUnpacker-Windows-GUI#1]
Thanks for the project!

It supports Inno Setup 5.x only, right? I got the following:

> Signature detected: Inno Setup Setup Data (6.0.0) (u)
> This is not directly supported, but i'll try to unpack it as version 5507
> ; Version detected: 6000 (Unicode)
> Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by jrathlev** [comment]
Unfortunately the included innounp.exe file was not up to date. Please download the updated
[installation package](https://www.rathlev-home.de/tools/download/innounpack-setup.exe)
