### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by MarkSpizu** [jrathlev/InnoUnpacker-Windows-GUI#10]
I tried with innounp050 and everything is unpacked fine.

But with your version I get this error

; Version detected: 5500 (Unicode)
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

So what's the problem?

**Comment by jrathlev** [comment]
Which setup do you want to unpack?

**Comment by MarkSpizu** [comment]
A setup made with 5.5.1-unicode

**Comment by MarkSpizu** [comment]
;InnoSetupVersion=5.5.0 (Unicode)

**Comment by bovirus** [comment]
@MarkSpizu

Could you please post a  link where can I download the exe installer that you want to unpack?

Thanks.

**Comment by MarkSpizu** [comment]
OK, here is the setup
[https://download.gg/en/file-13724489_62f7e9dfaaddb8d8](url)

As I said, no problem to unpack with innounp050.

**Comment by bovirus** [comment]
@MarkSpizu

Please post teh file in host like mega or similar.

**Comment by MarkSpizu** [comment]
Where? tell me a free one without account.

Why? my link is working [https://download.gg/en/file-13724489_62f7e9dfaaddb8d8](https://download.gg/en/file-13724489_62f7e9dfaaddb8d8)

**Comment by bovirus** [comment]
@MarkSpizu 

Confirm the problem.

@jrathlev 

With this installer A8dron.exe) innopunp 1.61.4 didn't work.
Innunp 0.50 and innoexxtract worked fie.

**Comment by jrathlev** [comment]
On Adron.exe, innounp 1.61 fails to read the language entries. This is strange because another Inno Setup file also made with Version 5500 (Unicode) can be extracted without any problems. Unfortunately debugging is very difficult at this point.

**Comment by jrathlev** [comment]
Fixed in innounp.exe  1.63
