### ISSUE TITLE
Version 1.8.1 - feedback

### ISSUE THREAD

**Issue by bovirus** [jrathlev/InnoUnpacker-Windows-GUI#12]
@jrathlev 

**Application name**

Note: the program name is "Inno Setup" and not "InnoSetup".

I believe that it's important to unify the use of application name in the installer

Yu mentioned it using three different names 

Innosetup unpack
Unpack InnoSetup
InnoUnpack

![image](https://user-images.githubusercontent.com/1262554/173332484-3a667bc7-fbc5-4dbb-a9a4-11b7e244f306.png)

![image](https://user-images.githubusercontent.com/1262554/173340525-093027ce-84a5-4caa-9c24-161fbd810fd9.png)

![image](https://user-images.githubusercontent.com/1262554/173334328-c9b202a3-a8ac-4e09-9049-7b364b4df241.png)

![image](https://user-images.githubusercontent.com/1262554/173334664-c37a5293-0440-4700-915b-dd212b790e88.png)

Innsoetup unpack (instalelr title)
Innsoetup unpack (application name)
Unpack innosetup (run application)
Unpack Innosetup (program group)
Unpack Innosetup (icond ecsription)
InnoUnapck (program name iN Windows program list)

The aplication is the same but are named in different way.
I beleieve the it's better to use a unique name for all issues (for me the best is Innounapck).

**Add multilanguage instalelr with prompt language**

currently your instalelr din't starta sking language.
It emans in my case if I instaleld previous version that not contain italian, the new version (that contain italian language) not use it but start in english.
To have italian I should uninstall 1,.8.0.0 and install 1.8.1..
Pelase enable in your Inno Setup script to read revuious language configurationa nd ask to the suer tos elect language. 

**_Application main window title_**

For me the tite of application main widnow on top left should be not a explanation but application anem + version

![image](https://user-images.githubusercontent.com/1262554/173333952-285abf92-7510-4bd9-a7db-23bd68a99c43.png)

**Generic standard icon in Windows program list**

![image](https://user-images.githubusercontent.com/1262554/173334917-ba877979-3dcc-4caf-b07a-a56890fe7412.png)

In Widnows program list there is a standard genric icon.

Pelase add in Inno Setup iss script the info to use a specifc icon for the program

**Comment by jrathlev** [comment]
Please check the updated setup.

**Comment by bovirus** [comment]
@jrathlev 

I download the new installer but seems the same.
I willw ait some minutes.

**Comment by jrathlev** [comment]
I prefer the language dialog if not required. The settings in the install script are:
`ShowLanguageDialog=auto
UsePreviousLanguage=no
`
The  dialog will only appear if the system language is not supported in the setup. Previous settings are ignored

**Comment by bovirus** [comment]
@jrathlev 

I beleive that most of the other sofwtare house use Inno Setup use a different approach.

Automatically detetct the OS language and if it's availble in teh application it set for the application.
But leave enabled the language dialog because the suer can select if he want another language.
No take care about rpevious settings for the language.

This si for me the best and logic choice.

Other problem reported (like different name for the application in different conetxt, genrico icon in Windows program list)s eems not fixed in the new installer.

Question: what's the real name (that should be unique) for this application

Innosetup unpack
Unpack innosetup
innounpack

Thanks.

**Comment by jrathlev** [comment]
I hope that all issues are fixed in version 1.8.2

**Comment by bovirus** [comment]
Another issue found.

Please check this in inno Setup script

**UninstallDisplayIcon=..\Unpack-View.ico**

If this path/file is not available is the reason for generic program icon in Windows program list.
