### ISSUE TITLE
innounp 1.61.4 (cmd line) - unpack error

### ISSUE THREAD

**Issue by bovirus** [jrathlev/InnoUnpacker-Windows-GUI#13]
@jrathlev 

Using latest installer Window GUi build (1,8.1) and innounp.exe (exe cmd line v. 1.61.4) I got two errors.

1. The .iss script contains at the end a NUL character.

2. The file

embeeded\WizardImage0.bmp
embedded\WizardSmallImage0.bmp

are wrong.
No error during opening .iss and create the exe.
But when I run the exe it report erro about Wziard bitmap.

Thanks.

**Comment by jrathlev** [comment]
Fixed in innounp 1.62

**Comment by bovirus** [comment]
@jrathlev 

Thanks for the fix.

Please take care that in web page the archive of sources for innounp point to version 1.61 (not to 1.62).

**Comment by jrathlev** [comment]
The Adron installer issue is still unsolved. Update of sources will follow
