### ISSUE TITLE
InnoUnpacker 1.8.3 - Feedbacks

### ISSUE THREAD

**Issue by bovirus** [jrathlev/InnoUnpacker-Windows-GUI#17]
Hi.

There is an issue in installer regarding the last window to run the application.

![image](https://user-images.githubusercontent.com/1262554/173558377-e48072d2-555d-4c7b-a200-d378b187ecd1.png)

I modified the Inno Setup script to fix this.

https://github.com/jrathlev/InnoUnpacker-Windows-GUI/pull/16

Thanks.

**Comment by jrathlev** [comment]
Done

**Comment by bovirus** [comment]
@jrathlev 

Please remind to merge PR and close it.
