### ISSUE TITLE
Program hangs

### ISSUE THREAD

**Issue by limelect** [jrathlev/InnoUnpacker-Windows-GUI#2]
I just took any installer , I did not even know if it was
compiled with Inno.
The program hangs.
I guess you do not use threads.

**Comment by jrathlev** [comment]
I tried different exe files and cannnot reproduce this issue. There are no special threads required because the program is only a GUI for the console application innounp which is started as a separate process. If this process does not respond, the program will return not later then 10s.

**Comment by limelect** [comment]
Sorry to say that in your case if it workes dose not mean that it is OK.
40 years of programming let me understand that

**Comment by jrathlev** [comment]
If you have a so long experience in programming, you should know that a statement "the program hangs" does not really help to find an issue. An error must be reproducable. So specify more details on what you are doing and check if the console application "innounp.exe" runs with your file from the command prompt.

**Comment by limelect** [comment]
I do not like to debug for people but i started it for you.
See my new issue.
