### ISSUE TITLE
POStrip - Add -o (output) option

### ISSUE THREAD

**Issue by bovirus** [jrathlev/InnoUnpacker-Windows-GUI#22]
@jrathlev 

Please iof you can add to PoStrip the -o (output file):
In otherway don't touch original .po but create a new .po file with stripepd comments.

Or if you like get filename and add a suffix (like .purged). Ex

Input file = test.po
Output file = test.purtged.po

**Comment by jrathlev** [comment]
This is not an InnoUnpacker issue. It should refer to the GnuGetText repository.

Nevertheless, here is the answer: PoStrip wll retain the original file as filename.bak.
