### ISSUE TITLE
Localization - Change po name in accordance with us

### ISSUE THREAD

**Issue by bovirus** [jrathlev/InnoUnpacker-Windows-GUI#27]
@jrathlev 

I propose to change the filename (po file) basing on use type

defaults.po/mo in 'projects' folder as projects,po/mo
defaults.po/mo in 'dialog' folder as dialogs,po/mo
defaults.po/mo in 'units' folder as units,po/mo

For me it's better and clear.

To avoid to check and believe that there are new language files when there are no changes in the strings but only in source reference could be an idea remove fro po language file reference to source lines.

Thanks.

**Comment by jrathlev** [comment]
1. defaults.po/mo in 'projects' folder will not be changed because this is determined by GnuGetText
2. 'dialogs' folder: The files are already dialogs,po/mo
3. 'units' folder: The files are already units,po/mo

**Comment by bovirus** [comment]
@jrathlev 

If you can please remove in .po files the refences aboput source lines.

If you made small changes to source code now the .po language files change (just change source references - not the string contents) then if a user monitor changes of these file see changes that are not really language string changes.

If you remove source lines refences the language file change only when there is  a string change.
