### ISSUE TITLE
Opening large installers times out

### ISSUE THREAD

**Issue by Azriel-S** [jrathlev/InnoUnpacker-Windows-GUI#28]
When I open large installers with InnoUnpack.exe, the results are truncated with an error message.

    143360  2024.08.28 07:57  C_\SolutionControlData\Shell\OPC-DANSrvUa.exe
       455  2024.08.28 07:57  C_\SolutionControlData\Shell\OPC-DANSrvUa.runtimeconfig.json
*** Error: The wait operation timed out

I believe the timeout is specified here in the Execute procedure.

wc:=WaitForSingleObject(pi.hProcess,10000); //=WAIT_TIMEOUT; // wait 10 s

Can this value be increased or made into a user changeable variable?

**Comment by Azriel-S** [comment]
I selected list Files with a large installer.  I get the "Timeout occured - continue anyway?" dialog. I press Yes, but it keeps coming back and never finishes.  It also doesn't show any progress.  It is like it is restarting if I press Yes.

**Comment by jrathlev** [comment]
Fixed in version 1.10.2
