### ISSUE TITLE
OK you forece me to debug

### ISSUE THREAD

**Issue by limelect** [jrathlev/InnoUnpacker-Windows-GUI#3]
1.There is no such place om my disk  'G:\Delphi Projects\rathlev-home_de\innounpack-s\InnoUnpack.exe'
    UnpProg:=ReadString(CfgSekt,iniUnp,'');
You have to take care of this

That why this  Execute(UnpProg+' -v',cbFile.Text,'','');
 dose not work.
and what kind of a program is this that execute it self ?
This is why i see in task manager 2 instances.
https://winmerge.org/ they have inno extractor works great.

I am willing to check your program once it works on one instance and loads reasonably well.

www.limelect.com you have on my site lots of free utilities all done with Delphi

Just found that if I stop debug under Delphi the 2 instances stay in memory.
Good luck.

**Comment by jrathlev** [comment]
If you would read the "readme.md" on the GitHub project page, you would have seen that "innunp.exe" is a separate program, see [Innounp](http://sourceforge.net/projects/innounp) on SourceForge.net
You can download the exe file from here:
https://www.rathlev-home.de/tools/download/innounp050.zip

My GUI provides a button to select the path to this program if it is not installed together with the InnoUnpack.exe
