### ISSUE TITLE
Unable to unpack Inno Setup v6.3.3

### ISSUE THREAD

**Issue by homes32** [jrathlev/InnoUnpacker-Windows-GUI#32]
Hello,

I'm unable to unpack an installer packed with Inno Setup 6.3.3. I'm using version innounp 1.75. Is 6.3.3 supported? Looking through the closed issues it appears that 6.3.1 was working correctly.

Example: [BeyondCompare5](https://www.scootersoftware.com/download)

```
*innounp*, the Inno Setup Unpacker. Version 1.75
Inno Setup archive: P:\Temp\BCompare-Setup.exe
=> Version detected: 6300 (Unicode)
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

The setup file is not corrupted. Run manually it installs fine.

**Comment by jrathlev** [comment]
BCompare-Setup.exe is not an original inno-setup.
