### ISSUE TITLE
InnoUnpacker Portable

### ISSUE THREAD

**Issue by skarsgal** [jrathlev/InnoUnpacker-Windows-GUI#33]
Hi,
I have used InnoUnpacker v1.10.2 (executable program as zip archive).
This program is not fully portable because it write the file 'InnoUnpack.ini' inside folder '%AppData%' instead of program folder, near  executable 'InnoUnpack.exe'.
Do You can fix this program behavior ?
Thanks.

**Comment by jrathlev** [comment]
Move to version 1.10.3
