### ISSUE TITLE
Please add the ability so select individual files to extract

### ISSUE THREAD

**Issue by skarsgal** [jrathlev/InnoUnpacker-Windows-GUI#35]
Hi,
I ask You to add the ability to select individual files to extract (as with **InnoEx** by cranq.fec: see on Softpedia.com: https://www.softpedia.com/get/Programming/Debuggers-Decompilers-Dissasemblers/InnoEx.shtml).
Thanks

**Comment by jrathlev** [comment]
You can specify a file filter to select any individual file or a group of files using wildcards
