### ISSUE TITLE
German language - Proposal for changes

### ISSUE THREAD

**Issue by bovirus** [jrathlev/InnoUnpacker-Windows-GUI#5]
@jrathlev 

**Not UTF-8 coding**

In poedit for German language is set ISO-8559-1 instead UTF8

"X-Poedit-SourceCharset: iso-8859-1\n"

should be

"X-Poedit-SourceCharset: UTF-8\n"

**Obsolete string**

In .po language file there are some obsolete strings that can be removed

#~ msgid "Archive info"
#~ msgstr "Archiv-Info"

#~ msgid "Select InnoSetup package"
#~ msgstr "InnoSetup-Paket auswaählen"

#~ msgid "About"
#~ msgstr "Über das Programm"

**Comment by jrathlev** [comment]
Because the sources are based on English this doesn't matter, but is still inconsistent, I shall fix  ist.
