### ISSUE TITLE
Proposal for change some strings

### ISSUE THREAD

**Issue by bovirus** [jrathlev/InnoUnpacker-Windows-GUI#6]
@jrathlev 

I have some proposal for string chanmges (in source and labnguage file)

#. MainForm..pnExtract..bbStart..Caption
#: UnpackMain.dfm:815
msgid "Start"

to

msgid "Extract"

because "Extract" button is more clear then "Start".

#. MainForm..pnExtract..cxStrip..Caption
#: UnpackMain.dfm:921
msgid "Strip paths"

to

msgid "Extract file without path"

because "Extract file without path" is more clear then "Strip paths".

#: UnpackMain.pas:235 UnpackMain.pas:264
msgid "Programs|*.exe|all|*.*"

to

msgid "Programs|*.exe|All Files|*.*"

"All files" is more standard then "all".

**Comment by jrathlev** [comment]
See the update to version 1.8.1
