### ISSUE TITLE
Installer multilanguage - Add italian language

### ISSUE THREAD

**Issue by bovirus** [jrathlev/InnoUnpacker-Windows-GUI#7]
@jrathlev 

Where can I find the .iss Inno Setup script that you used to compiler your application installer?

I would help you to add Italian language

Please give this opprtunity.

Note: program, please take care that program name is "inno Setup" (with space) and not "InnoSetupP".

Is this the list of file to translate

https://github.com/jrathlev/InnoUnpacker-Windows-GUI/blob/master/languages/dialogs/dialogs.po

https://github.com/jrathlev/InnoUnpacker-Windows-GUI/blob/master/languages/units/units.po

of course I have to edit it and copy the italin version in"it" subfolder.

Thanks. KR.

**Comment by jrathlev** [comment]
There is nothing left to do. The translations of units.po and dialogs.po are already available and uploaded.
The program specific translations are merged into the exe file and I added the Italian language to the Inno Setup. Please check if everything works as it should be.

**Comment by bovirus** [comment]
@jrathlev 

Could you please build a new version to etst Italian installer/GUI/etc?

Thanks.
